// <auto-generated />
namespace SistemaTienda1._5.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AdicicionTablaPedidoDetalle : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AdicicionTablaPedidoDetalle));
        
        string IMigrationMetadata.Id
        {
            get { return "202404060410508_AdicicionTablaPedidoDetalle"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
